/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import class_ispg.cours_dep_fac;
import static gui.cours_devC.gui_fs;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author HP
 */
public class devComUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form devComUI
     */
    public devComUI() {
        initComponents();
        ((BasicInternalFrameUI)getUI()).setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            boolean input(){
        return txt_cours.getText().length()>0&txt_nhr.getText().length()>0&select_annee.getSelectedItem()!=null
                &txt_cr.getText().length()>0;
    }
     void initlis(){
         txt_cours.setText("");

         txt_nhr.setText("");
         txt_cr.setText("");
         select_annee.removeAllItems();
         select_annee.addItem("BAC I");
         select_annee.addItem("BAC II");
         select_annee.addItem("BAC III");
         txt_com.setText("");
         cmbSemstr.removeAllItems();
         cmbSemstr.addItem("1");
         cmbSemstr.addItem("2");
         
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txt_cours = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nhr = new javax.swing.JTextField();
        select_annee = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbSemstr = new javax.swing.JComboBox<>();
        txt_cr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_com = new javax.swing.JTextArea();
        btn_quit = new javax.swing.JToggleButton();
        btn_ignor = new javax.swing.JToggleButton();
        btn_save = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Commentaire :");

        txt_cours.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Cours");

        jLabel9.setBackground(new java.awt.Color(0, 25, 50));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageGif/GUESTBOK.GIF"))); // NOI18N
        jLabel9.setText("       AJOUTER UN NOUVEAU COURS EN DEVELOPPEMENT COMMUN.");
        jLabel9.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Année");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Volume horaire");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        txt_nhr.setEditable(false);
        txt_nhr.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_nhr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nhrMouseClicked(evt);
            }
        });
        txt_nhr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhrActionPerformed(evt);
            }
        });
        txt_nhr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nhrKeyTyped(evt);
            }
        });

        select_annee.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        select_annee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAC I", "BAC II", "BAC III" }));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Nombre de crédit");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Semestre");

        cmbSemstr.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        cmbSemstr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        txt_cr.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_cr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_crKeyTyped(evt);
            }
        });

        txt_com.setColumns(20);
        txt_com.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_com.setLineWrap(true);
        txt_com.setRows(5);
        jScrollPane1.setViewportView(txt_com);

        btn_quit.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_quit.setText("Quitter");
        btn_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitActionPerformed(evt);
            }
        });

        btn_ignor.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_ignor.setText("Ignorer");
        btn_ignor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ignorActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_save.setText("Enregistrer");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jToggleButton1.setText("Visualiser");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btn_ignor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btn_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_cours, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_nhr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(cmbSemstr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txt_cr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(select_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_cours, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_nhr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbSemstr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(select_annee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_cr, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btn_ignor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btn_quit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nhrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nhrKeyTyped
        gui_fs.format_field(evt); // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhrKeyTyped

    private void txt_crKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_crKeyTyped
        gui_fs.format_field(evt); 
    }//GEN-LAST:event_txt_crKeyTyped

    private void btn_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(devComUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_quitActionPerformed

    private void btn_ignorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ignorActionPerformed
        initlis();
    }//GEN-LAST:event_btn_ignorActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        Date d=new Date();
        SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy");
        if(input())

        {
            gerer_volumeHoraire();
            if(JOptionPane.showConfirmDialog(this, "Voulez-vous l'enregistrer?")==JOptionPane.YES_OPTION){
                cours_dep_fac cf=new cours_dep_fac();
                cf.setCours(txt_cours.getText().toUpperCase());
                cf.setSanP(false);
                cf.setSagF(false);
                cf.setDevC(true);
                cf.setSoinF(false);
                cf.setNb_hr(Integer.parseInt(txt_nhr.getText()));
                cf.setCredit(Integer.parseInt(txt_cr.getText()));
                cf.setSemestr((String) cmbSemstr.getSelectedItem());
                cf.setAnnee(select_annee.getSelectedItem().toString());
                String dat=(df.format(d));
                cf.setCommentaire(txt_com.getText());
                cf.setDat_fixed(dat);
                if(cf.insert_cours()>0){
                    JOptionPane.showMessageDialog(this, "Effectuée");
                    initlis();
                }

            }else{
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "Insertion non effectuée", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Compléter des Informations obligatoires","Message d'attention",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        DevCotb dt=new DevCotb();
        general_GUI.deskpanne.removeAll();
        general_GUI.deskpanne.repaint();
        general_GUI.deskpanne.add(dt);
        try {
            dt.setMaximum(true);
            dt.show();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DevCotb.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
gerer_volumeHoraire();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txt_nhrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nhrMouseClicked
  
gerer_volumeHoraire();
    }//GEN-LAST:event_txt_nhrMouseClicked

    private void txt_nhrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_ignor;
    private javax.swing.JToggleButton btn_quit;
    private javax.swing.JToggleButton btn_save;
    private javax.swing.JComboBox<String> cmbSemstr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox<String> select_annee;
    private javax.swing.JTextArea txt_com;
    private javax.swing.JTextField txt_cours;
    private javax.swing.JTextField txt_cr;
    private javax.swing.JTextField txt_nhr;
    // End of variables declaration//GEN-END:variables
public void gerer_volumeHoraire(){
    
String s=txt_cr.getText();
        
if(s.length()>0){
    txt_nhr.setText(String.valueOf(Integer.parseInt(txt_cr.getText())*15));
}
}
}
