/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import class_ispg.connexiondata;
import class_ispg.gerer_fenetre;
import class_ispg.personnel;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class persoGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form persoGUI
     */
    public persoGUI() {
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
    ResultSet rs=null;
    int row;
     Object colonne[]={"Numéro matricule","Nom","Prenom","Sexe","Date de naissance","Nationalité","Colline/Qartier","Zone","Commune","Province",
       "Nom du Banque","Numéro de compte","Poste","Date Embauché","Type de contrat"};
    static String str=null;

    public boolean verify_input(){
    
        return !(txt_matri.getText()==null||txt_nom.getText()==null||txt_prenon.getText()==null||select_date.getDate()==null
                ||txt_commune.getText()==null||txt_province.getText()==null||txt_contra.getText()==null);
  
    }
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_matri = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_colline = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_prenon = new javax.swing.JTextField();
        select_genre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_province = new javax.swing.JTextField();
        nom_banque = new javax.swing.JTextField();
        txt_contra = new javax.swing.JTextField();
        txt_commune = new javax.swing.JTextField();
        num_compte = new javax.swing.JTextField();
        txt_quartier = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_nation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        select_date = new com.toedter.calendar.JDateChooser();
        btn_ignorer = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_liste = new javax.swing.JLabel();
        txtPoste = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        excel = new javax.swing.JLabel();
        btn_save = new javax.swing.JRadioButton();
        btn_modify = new javax.swing.JRadioButton();
        btn_supprimer = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_per = new javax.swing.JTable();

        txt_matri.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_matri.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_matri.setOpaque(false);
        txt_matri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matriActionPerformed(evt);
            }
        });
        txt_matri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_matriKeyTyped(evt);
            }
        });

        jLabel11.setText("Numero de compte");

        jLabel6.setText("Commune");

        jLabel2.setText("Nom");

        jLabel7.setText("Province");

        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_nom.setOpaque(false);
        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });
        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomKeyTyped(evt);
            }
        });

        jLabel1.setText("Numero Matricule");

        txt_colline.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_colline.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_colline.setOpaque(false);
        txt_colline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_collineActionPerformed(evt);
            }
        });
        txt_colline.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_collineKeyTyped(evt);
            }
        });

        jLabel10.setText("Type de contrat");

        txt_prenon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prenon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_prenon.setOpaque(false);
        txt_prenon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prenonActionPerformed(evt);
            }
        });
        txt_prenon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prenonKeyTyped(evt);
            }
        });

        select_genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme", "Autre" }));

        jLabel4.setText("Genre");

        jLabel3.setText("Prenom");

        jLabel8.setText("Date de naissance");

        jLabel5.setText("Colline/Quartier");

        jLabel9.setText("Banque");

        txt_province.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_province.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_province.setOpaque(false);
        txt_province.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_provinceActionPerformed(evt);
            }
        });
        txt_province.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_provinceKeyTyped(evt);
            }
        });

        nom_banque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom_banque.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        nom_banque.setOpaque(false);
        nom_banque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_banqueActionPerformed(evt);
            }
        });
        nom_banque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_banqueKeyTyped(evt);
            }
        });

        txt_contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_contra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_contra.setOpaque(false);
        txt_contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contraKeyTyped(evt);
            }
        });

        txt_commune.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_commune.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_commune.setOpaque(false);
        txt_commune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_communeActionPerformed(evt);
            }
        });
        txt_commune.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_communeKeyTyped(evt);
            }
        });

        num_compte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num_compte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        num_compte.setOpaque(false);
        num_compte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                num_compteKeyTyped(evt);
            }
        });

        txt_quartier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_quartier.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_quartier.setOpaque(false);
        txt_quartier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quartierActionPerformed(evt);
            }
        });
        txt_quartier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_quartierKeyTyped(evt);
            }
        });

        jLabel12.setText("Zone");

        txt_nation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txt_nation.setOpaque(false);
        txt_nation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nationActionPerformed(evt);
            }
        });
        txt_nation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nationKeyTyped(evt);
            }
        });

        jLabel13.setText("Nationalite");

        select_date.setFont(new java.awt.Font("Cambria Math", 1, 16)); // NOI18N
        select_date.setOpaque(false);
        select_date.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                select_dateAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btn_ignorer.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btn_ignorer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_denied_skin_type_7_20px_1.png"))); // NOI18N
        btn_ignorer.setText("Ignorer");
        btn_ignorer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ignorer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ignorerMouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_25px.png"))); // NOI18N

        txt_search.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_searchMouseExited(evt);
            }
        });
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        btn_liste.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btn_liste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Transaction_List_25px.png"))); // NOI18N
        btn_liste.setText("Liste");
        btn_liste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listeMouseClicked(evt);
            }
        });

        txtPoste.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPoste.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0))));
        txtPoste.setOpaque(false);
        txtPoste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPosteKeyTyped(evt);
            }
        });

        jLabel14.setText("Poste");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_print_30px.png"))); // NOI18N
        jLabel18.setText("Imprimer");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        excel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        excel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_ms_excel_30px.png"))); // NOI18N
        excel.setText("Exporter comme Fichier Excel");
        excel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excelMouseClicked(evt);
            }
        });

        btn_save.setText("Enregister");
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_save_25px.png"))); // NOI18N
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_modify.setText("Modifier");
        btn_modify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modify.setEnabled(false);
        btn_modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_edit_25px_1.png"))); // NOI18N
        btn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyActionPerformed(evt);
            }
        });

        btn_supprimer.setText("Supprimer");
        btn_supprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_supprimer.setEnabled(false);
        btn_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_25px.png"))); // NOI18N
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_matri)
                                .addComponent(txt_prenon)
                                .addComponent(select_genre, 0, 140, Short.MAX_VALUE)
                                .addComponent(txt_colline)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ignorer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_liste, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(excel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_commune, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_quartier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(num_compte, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(txt_nation)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_province, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(select_date, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nom_banque, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_matri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_quartier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(num_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_commune, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_nation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_province, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPoste, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_prenon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(select_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(select_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nom_banque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_colline, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_liste, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18)
                                        .addComponent(excel)
                                        .addComponent(btn_save)
                                        .addComponent(btn_modify)
                                        .addComponent(btn_supprimer))
                                    .addComponent(btn_ignorer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        table_per.setBackground(new java.awt.Color(0, 0, 51));
        table_per.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        table_per.setForeground(new java.awt.Color(255, 255, 255));
        table_per.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_per.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_perMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_per);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1776, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1776, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txt_nationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nationKeyTyped
    }//GEN-LAST:event_txt_nationKeyTyped
    private void txt_nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nationActionPerformed
    }//GEN-LAST:event_txt_nationActionPerformed
    private void txt_quartierKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quartierKeyTyped
    }//GEN-LAST:event_txt_quartierKeyTyped
    private void txt_quartierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quartierActionPerformed
    }//GEN-LAST:event_txt_quartierActionPerformed
    private void select_datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_select_datePropertyChange
        try {
            select_date.setSelectableDateRange(new SimpleDateFormat("MM-DD-YYYY").parse("01-01-0001"),new Date());
        } catch (ParseException ex) {
            Logger.getLogger(persoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_select_datePropertyChange
    private void select_dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_select_dateMouseClicked
    }//GEN-LAST:event_select_dateMouseClicked
    private void select_dateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_select_dateAncestorAdded
  
        Date date=new Date();
        select_date.setMaxSelectableDate(date);

       
        
        
    }//GEN-LAST:event_select_dateAncestorAdded
    private void num_compteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_compteKeyTyped
    }//GEN-LAST:event_num_compteKeyTyped
    private void txt_communeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_communeKeyTyped
    }//GEN-LAST:event_txt_communeKeyTyped
    private void txt_communeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_communeActionPerformed
    }//GEN-LAST:event_txt_communeActionPerformed
    private void txt_contraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contraKeyTyped
    }//GEN-LAST:event_txt_contraKeyTyped
    private void nom_banqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_banqueKeyTyped
    }//GEN-LAST:event_nom_banqueKeyTyped
    private void nom_banqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_banqueActionPerformed
    }//GEN-LAST:event_nom_banqueActionPerformed
    private void txt_provinceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_provinceKeyTyped
    }//GEN-LAST:event_txt_provinceKeyTyped
    private void txt_provinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_provinceActionPerformed
    }//GEN-LAST:event_txt_provinceActionPerformed
    private void txt_prenonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prenonKeyTyped
    }//GEN-LAST:event_txt_prenonKeyTyped
    private void txt_prenonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prenonActionPerformed
    }//GEN-LAST:event_txt_prenonActionPerformed
    private void txt_collineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_collineKeyTyped
    }//GEN-LAST:event_txt_collineKeyTyped
    private void txt_collineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_collineActionPerformed
    }//GEN-LAST:event_txt_collineActionPerformed
    private void txt_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyTyped
    }//GEN-LAST:event_txt_nomKeyTyped
    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
    }//GEN-LAST:event_txt_nomActionPerformed
    private void txt_matriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_matriKeyTyped
    }//GEN-LAST:event_txt_matriKeyTyped
    private void txt_matriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matriActionPerformed
    }//GEN-LAST:event_txt_matriActionPerformed

    private void btn_listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listeMouseClicked
play_table();        
    }//GEN-LAST:event_btn_listeMouseClicked

    private void btn_ignorerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ignorerMouseClicked
        initialise();
        table_per.setSelectionMode(0);
        btn_modify.setEnabled(false);
        btn_supprimer.setEnabled(false);
        btn_save.setEnabled(true);
        btn_liste.setEnabled(true);
    }//GEN-LAST:event_btn_ignorerMouseClicked

    private void txt_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseClicked

    }//GEN-LAST:event_txt_searchMouseClicked

    private void txt_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseEntered

    }//GEN-LAST:event_txt_searchMouseEntered

    private void txt_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseExited

    }//GEN-LAST:event_txt_searchMouseExited

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed

    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        DefaultTableModel tb_mod=(DefaultTableModel)table_per.getModel();
        String rechrc=txt_search.getText();
        TableRowSorter<DefaultTableModel>tm=new TableRowSorter<>(tb_mod);
        table_per.setRowSorter(tm);
        tm.setRowFilter(RowFilter.regexFilter(rechrc));
    }//GEN-LAST:event_txt_searchKeyTyped

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
gerer_fenetre.ImprimerLaTable(table_per);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void excelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excelMouseClicked
gerer_fenetre.export(table_per, ".xls");        // TODO add your handling code here:
    }//GEN-LAST:event_excelMouseClicked

    private void txtPosteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPosteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPosteKeyTyped

    private void btn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyActionPerformed
  row=table_per.getSelectedRow();
if(row>=0){
    str=(table_per.getModel().getValueAt(row, 0).toString());

        String date=sdf.format(select_date.getDate());

        try{
            if(verify_input()&&JOptionPane.showConfirmDialog(this , "Voulez vous modifier la séléction?")==JOptionPane.OK_OPTION){
                connexiondata.modifierDB("UPDATE personel SET n_matricule='"+txt_matri.getText()+"',nom='"+txt_nom.getText()+"',"
                    + "prenom='"+txt_prenon.getText()+"',sexe='"+select_genre.getSelectedItem().toString()+"',"
                    + "date_naissance='"+date+"',nationalite='"+txt_nation.getText()+"',col_naissance='"+txt_colline.getText()+"'"
                    + ",zone='"+txt_quartier.getText()+"',commune='"+txt_commune.getText()+"',province='"+txt_province.getText()+"',"
                    + "banque='"+nom_banque.getText()+"',n_compte='"+num_compte.getText()+"',poste='"+txtPoste.getText()+"',typecontrat='"+txt_contra.getText()+"'"
                    + "WHERE n_matricule='"+str+"'");
                JOptionPane.showMessageDialog(null, "La modification effectué avec succès","Message",JOptionPane.INFORMATION_MESSAGE);
                play_table();
                initialise();
                btn_save.setEnabled(true);
                btn_modify.setEnabled(false);
                btn_supprimer.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(this, "Opération a été annulée", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
            }
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this, "La mise à jour des données non effectué","ERREUR",JOptionPane.ERROR);
        } 
            }else{
       JOptionPane.showMessageDialog(this, "Séléctionnez la ligne à modifier");
   }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modifyActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
  if(verify_input())
  {
      personnel per=new personnel();

            if(JOptionPane.showConfirmDialog(this, "Voulez- vous l'ajouter?")==JOptionPane.OK_OPTION)
            {

                per.setN_matricule(txt_matri.getText());
                per.setNom(txt_nom.getText());
                per.setPrenom(txt_prenon.getText());
                per.setSexe(select_genre.getSelectedItem().toString());
                per.setCol_naiss(txt_colline.getText());
                per.setZone(txt_quartier.getText());
                per.setCom_naiss(txt_commune.getText());
                per.setProv_naiss(txt_province.getText());
                String dte=sdf.format(select_date.getDate());
                per.setDat_naiss(dte);
                per.setNationalite(txt_nation.getText());
                per.setBanque(nom_banque.getText());
                per.setNum_banque(num_compte.getText());
                per.setEnseignan(false);
                per.setDirection(false);
                per.setTravailleur(true);
                per.setPost(txtPoste.getText());
                per.setTyp_contrat(txt_contra.getText());
                Date d=new Date();
                String datenow=sdf.format(d);
                per.setDat_emb(datenow);
                if(per.insert()>0)
                {
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Operation réussie");
                    initialise();
                }
            }

        }
        else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Vérifier les champs obligatoires", "Attention", JOptionPane.WARNING_MESSAGE);
        }                  
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        row=table_per.getSelectedRow();
        if(row>=0){
        str=(table_per.getModel().getValueAt(row, 0).toString());

        if(JOptionPane.showConfirmDialog(null, "Voulez vous le supprimer?")==JOptionPane.OK_OPTION){
            connexiondata.modifierDB("DELETE FROM personel WHERE n_matricule='"+str+"'");
            JOptionPane.showMessageDialog(null, "Suppression effectué avec succès","Message",JOptionPane.INFORMATION_MESSAGE);
            play_table();
            initialise();
            btn_save.setEnabled(true);
            btn_modify.setEnabled(false);
            btn_supprimer.setEnabled(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Action refusée","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
                    }else{
       JOptionPane.showMessageDialog(this, "Séléctionnez la ligne à supprimer");
   }         
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void table_perMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_perMouseClicked
        play_content_table();
        btn_modify.setEnabled(true);
        btn_supprimer.setEnabled(true);
        btn_save.setEnabled(false);
        btn_liste.setEnabled(false);
    }//GEN-LAST:event_table_perMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_ignorer;
    private javax.swing.JLabel btn_liste;
    private javax.swing.JRadioButton btn_modify;
    private javax.swing.JRadioButton btn_save;
    private javax.swing.JRadioButton btn_supprimer;
    private javax.swing.JLabel excel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nom_banque;
    private javax.swing.JTextField num_compte;
    private com.toedter.calendar.JDateChooser select_date;
    private javax.swing.JComboBox<String> select_genre;
    private javax.swing.JTable table_per;
    private javax.swing.JTextField txtPoste;
    private javax.swing.JTextField txt_colline;
    private javax.swing.JTextField txt_commune;
    private javax.swing.JTextField txt_contra;
    private javax.swing.JTextField txt_matri;
    private javax.swing.JTextField txt_nation;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenon;
    private javax.swing.JTextField txt_province;
    private javax.swing.JTextField txt_quartier;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
//initialisation des JTextField
    public void initialise(){
                txt_search.setText("");
                txt_matri.setText("");
                txt_nom.setText("");
                txt_prenon.setText("");
                select_genre.removeAllItems();
                select_genre.repaint();
                select_genre.addItem("Homme");
                select_genre.addItem("Femme");
                select_genre.addItem("Autre");
                select_date.setDate(null);
                txt_nation.setText("");
                txt_colline.setText("");
                txt_quartier.setText("");
                txt_commune.setText("");
                txt_province.setText("");
                nom_banque.setText("");
                num_compte.setText("");
                txtPoste.setText("");
                txt_contra.setText("");
                
}
//joue dans les jtexteFields la ligne selectionée de la table
public void play_table(){
    DefaultTableModel df=new DefaultTableModel();
    table_per.setModel(df);

        df.setColumnIdentifiers(colonne);
        rs=connexiondata.extraireData("select *from personel where direction='"+true+"'");
        try {
            while(rs.next()){
                String matr=rs.getString("n_matricule");
                String nom=rs.getString("nom");
                String prenom=rs.getString("prenom");
                String sex=rs.getString("sexe");
                String naissance=rs.getString("date_naissance");
                String national=rs.getString("nationalite");
                String coll=rs.getString("col_naissance");
                String quartier=rs.getString("zone");
                String com=rs.getString("commune");
                String prov=rs.getString("province");
                String bank=rs.getString("banque");
                String num_comp=rs.getString("n_compte");
                String post=rs.getString("poste");
                String date_emb=rs.getString("date_embaucher");
                String typ_contrat=rs.getString("typecontrat");
                
                Object line[]={matr,nom,prenom,sex,naissance,national,coll,quartier,com,prov,bank,num_comp,post,date_emb,typ_contrat};
                df.addRow(line);
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(persoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
//fonction pour récuperer la ligne selectionner de la table dans les JTextFields
public void play_content_table(){
    
   row=table_per.getSelectedRow();
     str=(table_per.getModel().getValueAt(row, 0).toString());
     rs= connexiondata.extraireData("SELECT *FROM personel WHERE n_matricule='"+str+"'");
   
        try {
            while (rs.next()){
                txt_matri.setText(rs.getString("n_matricule"));
                txt_nom.setText(rs.getString("nom"));
                txt_prenon.setText(rs.getString("prenom"));
                select_genre.removeAllItems();
      
                select_genre.addItem(rs.getString("sexe"));
                select_date.setDate(rs.getDate("date_naissance"));
                txt_nation.setText(rs.getString("nationalite"));
                txt_colline.setText(rs.getString("col_naissance"));
                txt_quartier.setText(rs.getString("zone"));
                txt_commune.setText(rs.getString("commune"));
                txt_province.setText(rs.getString("province"));
                nom_banque.setText(rs.getString("banque"));
                num_compte.setText(rs.getString("n_compte"));
                txtPoste.setText(rs.getString("poste"));
                txt_contra.setText(rs.getString("typecontrat"));
            }
                
                } catch (SQLException ex) {
            Logger.getLogger(persoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
}
}
