/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suivi;

import class_ispg.connexiondata;
import class_ispg.gerer_fenetre;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public final class gestListCong extends javax.swing.JInternalFrame {

    /**
     * Creates new form gestListCong
     */
    public gestListCong() {
        initComponents();
        chargerMaTable();
        ((BasicInternalFrameUI)getUI()).setNorthPane(null);
    }
    DefaultTableModel dflt;
    void chargerMaTable(){
        dflt=new DefaultTableModel();
             Object[] colonne={"Numéro matricule","Nom","Prénom","Motif du congé", "Type du congé","Date d'aller",
            "Date de retour","Date d'enregistrement du congé","Retourné en Service"};
        dflt.setColumnIdentifiers(colonne);
        tblListConge.setModel(dflt);
        ResultSet set=connexiondata.extraireData("select n_matricule,nom,prenom,dateAller,dateRetour,motif,typeconge,dateFaite,retourne from "
                + "personel inner join conge where personel.idEmployer=conge.idEmployer");
        try {
            while(set.next()){
               Object row[]={set.getString("n_matricule"),set.getString("nom"),set.getString("prenom"),set.getString("motif"),
               set.getString("typeconge"),set.getString("dateAller"),set.getString("dateRetour"),set.getString("dateFaite"),
               set.getString("retourne")}; 
               dflt.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(gestListCong.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    //methode de suppression
    int row=-1;
    void delete()
    {
        row=tblListConge.getSelectedRow();
        if(row>=0){
            if(JOptionPane.showConfirmDialog(this, "Confirmer la suppression")==JOptionPane.OK_OPTION)
            {

            String val=tblListConge.getValueAt(row, 7).toString();
            connexiondata.modifierDB("delete from conge where dateFaite='"+val+"'");
            JOptionPane.showMessageDialog(this, "Supprimé avec succès");
            chargerMaTable();
            row=-1;
            }else{
               JOptionPane.showMessageDialog(this, "Accès non confirmé"," ",JOptionPane.ERROR_MESSAGE);
  
            }
        }else{
            JOptionPane.showMessageDialog(this, "Séléctionner d'abord la ligne");
        }
    }
    
    //La mise à jour des données
    void UpdateTable()
    {
        row=tblListConge.getSelectedRow();
        if(row>=0){
            if(JOptionPane.showConfirmDialog(this, "Confirmer la mise à jour des données")==JOptionPane.OK_OPTION)
            {
             String update="Oui";
            String val=tblListConge.getValueAt(row, 7).toString();
            connexiondata.modifierDB("update conge set retourne='"+update+"' where dateFaite='"+val+"'");
            JOptionPane.showMessageDialog(this, "La mise à jour des données effectué avec succès");
            
            chargerMaTable();
            row=-1;
            }else{
                getToolkit().beep();
                  JOptionPane.showMessageDialog(this, "Accès non confirmé"," ",JOptionPane.ERROR_MESSAGE);
              }
        }else{
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Séléctionner d'abord la ligne");
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListConge = new javax.swing.JTable();
        search = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        playPan = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        tblListConge.setBackground(new java.awt.Color(0, 51, 51));
        tblListConge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        tblListConge.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        tblListConge.setForeground(new java.awt.Color(255, 255, 255));
        tblListConge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListConge);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });

        jRadioButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageGif/PCSEARCH.GIF"))); // NOI18N

        playPan.setBackground(new java.awt.Color(0, 51, 102));

        jRadioButton1.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButton1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Retourné en service");
        jRadioButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_double_left_30px.png"))); // NOI18N
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButton2.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Supprimer");
        jRadioButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_25px.png"))); // NOI18N
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButton3.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Imprimer");
        jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Send_to_Printer_30px.png"))); // NOI18N
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(0, 51, 153));
        jRadioButton4.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Exporter comme fichier excel");
        jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_ms_excel_30px.png"))); // NOI18N
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playPanLayout = new javax.swing.GroupLayout(playPan);
        playPan.setLayout(playPanLayout);
        playPanLayout.setHorizontalGroup(
            playPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playPanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jRadioButton4)
                .addGap(0, 0, 0))
        );
        playPanLayout.setVerticalGroup(
            playPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playPanLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(playPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(playPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(playPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
gerer_fenetre.ImprimerLaTable(tblListConge);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
gerer_fenetre.export(tblListConge, ".xls");        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
dflt=new DefaultTableModel();
String string=search.getText();
        gerer_fenetre.gererLaRecherche(tblListConge, dflt, search, string);        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyTyped

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
delete();

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
UpdateTable();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel playPan;
    private javax.swing.JTextField search;
    private javax.swing.JTable tblListConge;
    // End of variables declaration//GEN-END:variables
}
