/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tables;

import paiement.paiement_tab;
import class_ispg.connexiondata;
import class_ispg.gerer_fenetre;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import static paiement.paiement_tab.requestHist;

/**
 *
 * @author HP
 */
public final class tb_history extends javax.swing.JInternalFrame {

        /**
         * Creates new form tb_history
         */
        public tb_history() {
            initComponents();
//            paiement_tab tp=new paiement_tab();
            tp.charg_tabl(tb_paiement_hist,requestHist);
           ((BasicInternalFrameUI)getUI()).setNorthPane(null);
        }
        paiement_tab tp=new paiement_tab();
//    DefaultTableModel def_mod=new DefaultTableModel();
//selection de l'historique
//    public void show_history(){
//        tb_paiement_hist.setModel(def_mod);
//        Object[] colonne={"Numéro matricule","Nom","Prenom","Numéro de compte","Nom de la Banque","Salaire Total","Retenu Source"
//                ,"Date de paiement","Commentaire"};
//        def_mod.setColumnIdentifiers(colonne);
//        ResultSet hist=connexiondata.extraireData("select n_matricule,nom,prenom,banque,n_compte,salTot,salPay,frInss,"
//                + "frMut,date_payer,commentaire from personel,hist_paiement where personel.idEmployer=hist_paiement.idEmpl");
//        try {
//            while(hist.next()){
//            Object ligne[]={hist.getString("n_matricule"),hist.getString("nom"),hist.getString("prenom"),
//                hist.getString("banque"),hist.getString("n_compte"),hist.getString("salTot"),hist.getString("salPay"),
//                hist.getString("frInss"),hist.getString("frMut"),hist.getString("date_payer"),hist.getString("commentaire")};
//            def_mod.addRow(ligne);               
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(paiement_tab.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_paiement_hist = new javax.swing.JTable();

        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(18, 30, 49));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_25px.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 40, 30, 60);

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255))));
        jTextField1.setOpaque(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 40, 230, 40);

        jRadioButton4.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Exporter comme excel");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_ms_excel_48px.png"))); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(880, 40, 210, 50);

        jRadioButton2.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Retirer");
        jRadioButton2.setToolTipText("");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_delete_48px.png"))); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(740, 40, 130, 50);

        jRadioButton3.setBackground(new java.awt.Color(0, 51, 51));
        jRadioButton3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Imprimer");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_print_48px_1.png"))); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(530, 40, 120, 50);

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1530, 140);

        tb_paiement_hist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_paiement_hist);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 140, 1360, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        gerer_fenetre.export(tb_paiement_hist, ".xls");        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        gerer_fenetre.ImprimerLaTable(tb_paiement_hist);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    int row=-1;
    row=tb_paiement_hist.getSelectedRow();
   
   if(row>=0){
       String s=tb_paiement_hist.getValueAt(row, 11).toString();
       if(JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer?")==JOptionPane.OK_OPTION)
               {

       connexiondata.modifierDB("delete from hist_paiement where date_payer='"+s+"'");
       JOptionPane.showMessageDialog(this, "La suppression a été effectué");
       
       tp.charg_tabl(tb_paiement_hist,requestHist);
       }else{
              getToolkit().beep();
        JOptionPane.showMessageDialog(this, "Les droits de supprimer non accorder","",JOptionPane.ERROR_MESSAGE);
        tp.charg_tabl(tb_paiement_hist,requestHist);
       }
   }else{
       getToolkit().beep();
     JOptionPane.showMessageDialog(this, "séléctionner la ligne à supprimer","",JOptionPane.WARNING_MESSAGE);
    
   }
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tb_paiement_hist;
    // End of variables declaration//GEN-END:variables
}
